-- 코드를 입력하세요
SELECT PD.PRODUCT_CODE AS PRODUCT_CODE, SUM(OS.SALES_AMOUNT) * PD.PRICE AS SALES
FROM OFFLINE_SALE AS OS
LEFT JOIN PRODUCT AS PD ON OS.PRODUCT_ID = PD.PRODUCT_ID
GROUP BY PD.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC